### ISSUE TITLE
[Bug][Windows][Crash] Crashes on latest nightly build

### ISSUE THREAD

**Issue by 209CATrus** [jamespetts/simutrans-extended#153]
All crashes end with "**...memory can't be "read".**"

It feels like minefield now, but these are only ones i stumbled upon so far:
Cases:
1. **World generation**
2. Clicking with signal reservation mode in main menu world, exact conditions for this remain unknown.

Windows XP SP3 32-bit

**Comment by jamespetts** [comment]
Thank you for your report. I believe that I have fixed the issue on world generation - I should be grateful if you could re-test with to-morrow's nightly build.

As to the second item, I am afraid that I am not clear from the description what it is exactly that you are doing that gives rise to the crash. Can you elaborate?

**Comment by 209CATrus** [comment]
Thanks, going to check it out.

For second error to appear i do the following steps:

1. I close the New Map menu to play in default world
2. I enter the signal reservation mode ('b') and play around a bit (break reservations and sometimes click on ground)
3. Error arrives shortly, but not instantly and with slightly different time periods each time

**Comment by 209CATrus** [comment]
Yes, worldgen works now, thank you very much!

**Comment by 209CATrus** [comment]
Fatal error (not windows related, gladly): sim_new_handler() - OUT OF MEMORY

Error occured when i tried to send fifth (last) tram of copied bunch

**Comment by jamespetts** [comment]
For the latest report, I will need a copy of the saved game in which this error occurred to attempt to reproduce it.

Note that, for this sort of error, it is possible that it is caused by your system being low on memory.

**Comment by jamespetts** [comment]
I am afraid that I am not able to reproduce the problem reported with signal reservations. Are you able to be more precise about a set of instructions that can truly reliably reproduce this issue?

**Comment by 209CATrus** [comment]
Okay, i double checked that error on latest nigthly and it's still present. To put it simply, you just need to get access to default (that long one with mines at the top) background map from main menu. Then you just turn on signal reservation mode and click anywhere you want on the map. 

As for latest problem, no way it's just simple memory issue. I played on map twice as big, and the only thing i had was just 1 ship and 5 trams. It looks more like memory leak or something. I hope i could get save for you to reproduce that shortly

**Comment by jamespetts** [comment]
That is

**Comment by jamespetts** [comment]
This is exactly what I tried, but I am afraid that I was not able to reproduce this issue, either with a debug build or the latest nightly binary. I will need more precise detail as to exactly where you clicked so that I can check whether this is reproducible.

As to the second problem, I shall look forward to receiving a saved game reproduction case in due course.

**Comment by 209CATrus** [comment]
Okay, seems that latest problem was sheer luck, cause in new game and relatively same setup everything so far is okay. 
The crash problem doesn't seem to appear inside regular map, at least random clicking is okay (I haven't build any advanced rail systems yet).

I guess there isn't any gamebreaking bugs at the moment, so i think issue so far is solved. Thanks for support and sorry for wasting your time.

If you really interested in reproducing that crash, i suggest using VM with WinXP SP3, because everything i can provide is number of function from error message.

**Comment by jamespetts** [comment]
Thank you for confirming. Please let me know if you manage to produce a reliable reproduction case for either issue in the future.
