### ISSUE TITLE
Trying to save a pointer with rdwr_long()

### ISSUE THREAD

**Issue by abadger** [jamespetts/simutrans-extended#51]
https://github.com/jamespetts/simutrans-extended/commit/7d09ea4d9d1f18a9f9b237f8a7167259eb8f4c6f#diff-332b2e33ca42c2bdbe716fd1e63f4574R457

tries to cast a pointer to powernet_t to a uint32.  That can have problems on 64bit systems where pointers are uint64. (The default Makefile tells gcc to error when a cast would lose precision.)

The comments imply that the information is saved but never utilized when reloading.  So perhaps the easiest thing to do here is to save a dummy, constant 32bit value into that position.

Always saving a 64bit value and converting from a 32bit pointer to 64bit on 32bit systems may also work but it looks like there might be some compiler-specific details which make that trickier than simply casting: http://stackoverflow.com/questions/25039796/cast-from-32-bit-address-to-64-bit-integer-yields-unexpected-results

**EDIT:** Changed to say the code could save a dummy 32bit value.  I assume that saving a dummy 64bit value would break compatibility?

**Comment by jamespetts** [comment]
As the value is not used, I very much doubt that this will make any difference, but I have replaced it with a dummy value out of an abundance of caution. Thank you for checking this.

**Comment by abadger** [comment]
Fix in https://github.com/jamespetts/simutrans-extended/commit/b9697dfa6ed8a3b5b0c9b3ca76f09b1aa50ab7d4   confirmed.  I can now compile using the default gcc compile flags.
