### ISSUE TITLE
binaries in the repository

### ISSUE THREAD

**Issue by gschenk** [jamespetts/simutrans-extended#6]
simutrans/Simutrans-Experimental.exe
and 
Nettool-Experimental.exe
are included in the repository, and should better be removed.

**Comment by abadger** [comment]
* Simutrans-Experimental.exe was removed here: https://github.com/jamespetts/simutrans-extended/commit/04bb643c228b6bd40ff88f1ec73caa6677ec4308
* Nettool-Experimental.exe was removed here: https://github.com/jamespetts/simutrans-extended/commit/fbbc07cf0c8a48732cc1e316eb3f505d3909569a

This issue could be closed.
